name: Server

on: [ push ]

defaults:
  run:
    working-directory: ./images/Server

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: BuildX
        uses: docker/setup-buildx-action@v2
      -
        name: Authorization
        uses: docker/login-action@v2
        with:
          username: iantorres
          password: ${{ secrets.DOCKER_HUB_AUTHENTICATION_TOKEN }}
      -
        name: B & P
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: iantorres/server:latest
          context: ./images/Server
          file: images/Server/Dockerfile
          no-cache: true
      -
        name: Digest
        run: echo ${{ steps.docker_build.outputs.digest }}